import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
try:
    from .config import Config
except (ImportError, ValueError):
    from config import Config

class EmailHelper:
    
    @staticmethod
    def send_prediction_email(user_email, parent_email, user_name, disease_type, prediction_result, risk_score, gemini_recommendation, hospitals):
        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f'Medisense AI - {disease_type} Prediction Report'
            msg['From'] = Config.MAIL_DEFAULT_SENDER
            msg['To'] = parent_email
            
            hospital_list = ""
            if hospitals:
                hospital_list = "<h3>Recommended Hospitals Near You:</h3><ul>"
                for hospital in hospitals:
                    hospital_list += f"<li><strong>{hospital['name']}</strong><br>Distance: {hospital['distance']} km<br><a href='{hospital['google_maps_link']}' target='_blank'>View on Google Maps</a></li>"
                hospital_list += "</ul>"
            
            html_content = f"""
            <html>
                <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                    <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #0A3323; border-radius: 10px;">
                        <h2 style="color: #0A3323; text-align: center;">Medisense AI Health Report</h2>
                        
                        <div style="background-color: #F7F4D5; padding: 15px; border-radius: 5px; margin: 20px 0;">
                            <h3 style="color: #0A3323;">Patient Information</h3>
                            <p><strong>Name:</strong> {user_name}</p>
                            <p><strong>Email:</strong> {user_email}</p>
                            <p><strong>Disease Type:</strong> {disease_type}</p>
                            <p><strong>Prediction Result:</strong> <span style="color: #D3968C; font-weight: bold;">{prediction_result}</span></p>
                            <p><strong>Risk Score:</strong> {risk_score}%</p>
                        </div>
                        
                        <div style="background-color: #839958; color: white; padding: 15px; border-radius: 5px; margin: 20px 0;">
                            <h3>AI Recommendations</h3>
                            <p style="white-space: pre-wrap;">{gemini_recommendation}</p>
                        </div>
                        
                        {hospital_list}
                        
                        <div style="margin-top: 30px; padding: 15px; background-color: #105666; color: white; border-radius: 5px; text-align: center;">
                            <p><strong>Important:</strong> This is an AI-generated report. Please consult a healthcare professional for proper diagnosis and treatment.</p>
                        </div>
                        
                        <p style="text-align: center; margin-top: 20px; color: #0A3323;">
                            <em>Generated by Medisense AI</em>
                        </p>
                    </div>
                </body>
            </html>
            """
            
            html_part = MIMEText(html_content, 'html')
            msg.attach(html_part)
            
            with smtplib.SMTP(Config.MAIL_SERVER, Config.MAIL_PORT) as server:
                server.starttls()
                server.login(Config.MAIL_USERNAME, Config.MAIL_PASSWORD)
                server.send_message(msg)
            
            return True
        
        except Exception as e:
            print(f"Email sending failed: {str(e)}")
            return False